server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: 6606

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 40036119098-o9agdelmnon6dek2n0ijgs2k5lc6n3mk.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email

app:
  jwt:
    secret: my-super-secret-key-that-is-at-least-32-characters-long
    expiration-ms: 86400000

  cors:
    allowed-origins: http://localhost:3000

  oauth2:
    authorized-redirect-uris: http://localhost:3000/oauth2/redirect

logging:
  level:
    org.springframework.security: DEBUG